export type LocationLanguageOption = {
  countryCode: string;
  name: string;
  googleId: number;
};

export const LOCATION_LANGUAGE_OPTIONS = [
  { countryCode: "ar", name: "Arabic", googleId: 1019 },
  { countryCode: "bn", name: "Bengali", googleId: 1056 },
  { countryCode: "bg", name: "Bulgarian", googleId: 1020 },
  { countryCode: "ca", name: "Catalan", googleId: 1038 },
  { countryCode: "zh_CN", name: "Chinese (simplified)", googleId: 1017 },
  { countryCode: "zh_TW", name: "Chinese (traditional)", googleId: 1018 },
  { countryCode: "hr", name: "Croatian", googleId: 1039 },
  { countryCode: "cs", name: "Czech", googleId: 1021 },
  { countryCode: "da", name: "Danish", googleId: 1009 },
  { countryCode: "nl", name: "Dutch", googleId: 1010 },
  { countryCode: "en", name: "English", googleId: 1000 },
  { countryCode: "et", name: "Estonian", googleId: 1043 },
  { countryCode: "tl", name: "Filipino", googleId: 1042 },
  { countryCode: "fi", name: "Finnish", googleId: 1011 },
  { countryCode: "fr", name: "French", googleId: 1002 },
  { countryCode: "de", name: "German", googleId: 1001 },
  { countryCode: "el", name: "Greek", googleId: 1022 },
  { countryCode: "gu", name: "Gujarati", googleId: 1072 },
  { countryCode: "iw", name: "Hebrew", googleId: 1027 },
  { countryCode: "hi", name: "Hindi", googleId: 1023 },
  { countryCode: "hu", name: "Hungarian", googleId: 1024 },
  { countryCode: "is", name: "Icelandic", googleId: 1026 },
  { countryCode: "id", name: "Indonesian", googleId: 1025 },
  { countryCode: "it", name: "Italian", googleId: 1004 },
  { countryCode: "ja", name: "Japanese", googleId: 1005 },
  { countryCode: "kn", name: "Kannada", googleId: 1086 },
  { countryCode: "ko", name: "Korean", googleId: 1012 },
  { countryCode: "lv", name: "Latvian", googleId: 1028 },
  { countryCode: "lt", name: "Lithuanian", googleId: 1029 },
  { countryCode: "ms", name: "Malay", googleId: 1102 },
  { countryCode: "ml", name: "Malayalam", googleId: 1098 },
  { countryCode: "mr", name: "Marathi", googleId: 1101 },
  { countryCode: "no", name: "Norwegian", googleId: 1013 },
  { countryCode: "fa", name: "Persian", googleId: 1064 },
  { countryCode: "pl", name: "Polish", googleId: 1030 },
  { countryCode: "pt", name: "Portuguese", googleId: 1014 },
  { countryCode: "pa", name: "Punjabi", googleId: 1110 },
  { countryCode: "ro", name: "Romanian", googleId: 1032 },
  { countryCode: "ru", name: "Russian", googleId: 1031 },
  { countryCode: "sr", name: "Serbian", googleId: 1035 },
  { countryCode: "sk", name: "Slovak", googleId: 1033 },
  { countryCode: "sl", name: "Slovenian", googleId: 1034 },
  { countryCode: "es", name: "Spanish", googleId: 1003 },
  { countryCode: "sv", name: "Swedish", googleId: 1015 },
  { countryCode: "ta", name: "Tamil", googleId: 1130 },
  { countryCode: "te", name: "Telugu", googleId: 1131 },
  { countryCode: "th", name: "Thai", googleId: 1044 },
  { countryCode: "tr", name: "Turkish", googleId: 1037 },
  { countryCode: "uk", name: "Ukrainian", googleId: 1036 },
  { countryCode: "ur", name: "Urdu", googleId: 1041 },
  { countryCode: "vi", name: "Vietnamese", googleId: 1040 }
]